const layout = [
  [
    {
      key: 'Backquote',
      type: 'symbol',
      text: {
        en: '`',
        enCapital: '`',
        lt: '`',
        ltCapital: '`',
        enSpecial: '~',
        ltSpecial: '~',
      },
    },
    {
      key: 'Digit1',
      type: 'symbol',
      text: {
        en: '1',
        enCapital: '1',
        lt: 'ą',
        ltCapital: 'Ą',
        enSpecial: '!',
        ltSpecial: 'Ą',
      },
    },
    {
      key: 'Digit2',
      type: 'symbol',
      text: {
        en: '2',
        enCapital: '2',
        lt: 'č',
        ltCapital: 'Č',
        enSpecial: '@',
        ltSpecial: 'Č',
      },
    },
    {
      key: 'Digit3',
      type: 'symbol',
      text: {
        en: '3',
        enCapital: '3',
        lt: 'ę',
        ltCapital: 'Ę',
        enSpecial: '#',
        ltSpecial: 'Ę',
      },
    },
    {
      key: 'Digit4',
      type: 'symbol',
      text: {
        en: '4',
        enCapital: '4',
        lt: 'ė',
        ltCapital: 'Ė',
        enSpecial: '$',
        ltSpecial: 'Ė',
      },
    },
    {
      key: 'Digit5',
      type: 'symbol',
      text: {
        en: '5',
        enCapital: '5',
        lt: 'į',
        ltCapital: 'Į',
        enSpecial: '%',
        ltSpecial: 'Į',
      },
    },
    {
      key: 'Digit6',
      type: 'symbol',
      text: {
        en: '6',
        enCapital: '6',
        lt: 'š',
        ltCapital: 'Š',
        enSpecial: '^',
        ltSpecial: 'Š',
      },
    },
    {
      key: 'Digit7',
      type: 'symbol',
      text: {
        en: '7',
        enCapital: '7',
        lt: 'ų',
        ltCapital: 'Ų',
        enSpecial: '&',
        ltSpecial: 'Ų',
      },
    },
    {
      key: 'Digit8',
      type: 'symbol',
      text: {
        en: '8',
        enCapital: '8',
        lt: 'ū',
        ltCapital: 'Ū',
        enSpecial: '*',
        ltSpecial: 'Ū',
      },
    },
    {
      key: 'Digit9',
      type: 'symbol',
      text: {
        en: '9',
        enCapital: '9',
        lt: '9',
        ltCapital: '9',
        enSpecial: '(',
        ltSpecial: '(',
      },
    },
    {
      key: 'Digit0',
      type: 'symbol',
      text: {
        en: '0',
        enCapital: '0',
        lt: '0',
        ltCapital: '0',
        enSpecial: ')',
        ltSpecial: ')',
      },
    },
    {
      key: 'Minus',
      type: 'symbol',
      text: {
        en: '-',
        enCapital: '-',
        lt: '-',
        ltCapital: '-',
        enSpecial: '_',
        ltSpecial: '_',
      },
    },
    {
      key: 'Equal',
      type: 'symbol',
      text: {
        en: '=',
        enCapital: '=',
        lt: 'ž',
        ltCapital: 'Ž',
        enSpecial: '+',
        ltSpecial: 'Ž',
      },
    },
    {
      key: 'Backspace',
      type: 'function',
      text: {
        en: 'Backspace',
        enCapital: 'Backspace',
        lt: 'Backspace',
        ltCapital: 'Backspace',
        enSpecial: 'Backspace',
        ltSpecial: 'Backspace',
      },
      width: 'width-double',
    },
  ],
  [
    {
      key: 'Tab',
      type: 'function',
      text: {
        en: 'Tab',
        enCapital: 'Tab',
        lt: 'Tab',
        ltCapital: 'Tab',
        enSpecial: 'Tab',
        ltSpecial: 'Tab',
      },
      width: 'width-2',
    },
    {
      key: 'KeyQ',
      type: 'symbol',
      text: {
        en: 'q',
        enCapital: 'Q',
        lt: 'q',
        ltCapital: 'Q',
        enSpecial: 'Q',
        ltSpecial: 'Q',
      },
    },
    {
      key: 'KeyW',
      type: 'symbol',
      text: {
        en: 'w',
        enCapital: 'W',
        lt: 'w',
        ltCapital: 'W',
        enSpecial: 'W',
        ltSpecial: 'W',
      },
    },
    {
      key: 'KeyE',
      type: 'symbol',
      text: {
        en: 'e',
        enCapital: 'E',
        lt: 'e',
        ltCapital: 'E',
        enSpecial: 'E',
        ltSpecial: 'E',
      },
    },
    {
      key: 'KeyR',
      type: 'symbol',
      text: {
        en: 'r',
        enCapital: 'R',
        lt: 'r',
        ltCapital: 'R',
        enSpecial: 'R',
        ltSpecial: 'R',
      },
    },
    {
      key: 'KeyT',
      type: 'symbol',
      text: {
        en: 't',
        enCapital: 'T',
        lt: 't',
        ltCapital: 'T',
        enSpecial: 'T',
        ltSpecial: 'T',
      },
    },
    {
      key: 'KeyY',
      type: 'symbol',
      text: {
        en: 'y',
        enCapital: 'Y',
        lt: 'y',
        ltCapital: 'Y',
        enSpecial: 'Y',
        ltSpecial: 'Y',
      },
    },
    {
      key: 'KeyU',
      type: 'symbol',
      text: {
        en: 'u',
        enCapital: 'U',
        lt: 'u',
        ltCapital: 'U',
        enSpecial: 'U',
        ltSpecial: 'U',
      },
    },
    {
      key: 'KeyI',
      type: 'symbol',
      text: {
        en: 'i',
        enCapital: 'I',
        lt: 'i',
        ltCapital: 'I',
        enSpecial: 'I',
        ltSpecial: 'I',
      },
    },
    {
      key: 'KeyO',
      type: 'symbol',
      text: {
        en: 'o',
        enCapital: 'O',
        lt: 'o',
        ltCapital: 'O',
        enSpecial: 'O',
        ltSpecial: 'O',
      },
    },
    {
      key: 'KeyP',
      type: 'symbol',
      text: {
        en: 'p',
        enCapital: 'P',
        lt: 'p',
        ltCapital: 'P',
        enSpecial: 'P',
        ltSpecial: 'P',
      },
    },
    {
      key: 'BracketLeft',
      type: 'symbol',
      text: {
        en: '[',
        enCapital: '[',
        lt: '[',
        ltCapital: '[',
        enSpecial: '{',
        ltSpecial: '{',
      },
    },
    {
      key: 'BracketRight',
      type: 'symbol',
      text: {
        en: ']',
        enCapital: ']',
        lt: ']',
        ltCapital: ']',
        enSpecial: '}',
        ltSpecial: '}',
      },
    },
    {
      key: 'Backslash',
      type: 'symbol',
      text: {
        en: '\\',
        enCapital: '\\',
        lt: '\\',
        ltCapital: '\\',
        enSpecial: '|',
        ltSpecial: '|',
      },
    },
    {
      key: 'Delete',
      type: 'function',
      text: {
        en: 'Del',
        enCapital: 'Del',
        lt: 'Del',
        ltCapital: 'Del',
        enSpecial: 'Del',
        ltSpecial: 'Del',
      },
      width: 'width-2',
    },
  ],
  [
    {
      key: 'CapsLock',
      type: 'function',
      text: {
        en: 'Caps',
        enCapital: 'Caps',
        lt: 'Caps',
        ltCapital: 'Caps',
        enSpecial: 'Caps',
        ltSpecial: 'Caps',
      },
      width: 'width-double',
    },
    {
      key: 'KeyA',
      type: 'symbol',
      text: {
        en: 'a',
        enCapital: 'A',
        lt: 'a',
        ltCapital: 'A',
        enSpecial: 'A',
        ltSpecial: 'A',
      },
    },
    {
      key: 'KeyS',
      type: 'symbol',
      text: {
        en: 's',
        enCapital: 'S',
        lt: 's',
        ltCapital: 'S',
        enSpecial: 'S',
        ltSpecial: 'S',
      },
    },
    {
      key: 'KeyD',
      type: 'symbol',
      text: {
        en: 'd',
        enCapital: 'D',
        lt: 'd',
        ltCapital: 'D',
        enSpecial: 'D',
        ltSpecial: 'D',
      },
    },
    {
      key: 'KeyF',
      type: 'symbol',
      text: {
        en: 'f',
        enCapital: 'F',
        lt: 'f',
        ltCapital: 'F',
        enSpecial: 'F',
        ltSpecial: 'F',
      },
    },
    {
      key: 'KeyG',
      type: 'symbol',
      text: {
        en: 'g',
        enCapital: 'G',
        lt: 'g',
        ltCapital: 'G',
        enSpecial: 'G',
        ltSpecial: 'G',
      },
    },
    {
      key: 'KeyH',
      type: 'symbol',
      text: {
        en: 'h',
        enCapital: 'H',
        lt: 'h',
        ltCapital: 'H',
        enSpecial: 'H',
        ltSpecial: 'H',
      },
    },
    {
      key: 'KeyJ',
      type: 'symbol',
      text: {
        en: 'j',
        enCapital: 'J',
        lt: 'j',
        ltCapital: 'J',
        enSpecial: 'J',
        ltSpecial: 'J',
      },
    },
    {
      key: 'KeyK',
      type: 'symbol',
      text: {
        en: 'k',
        enCapital: 'K',
        lt: 'k',
        ltCapital: 'K',
        enSpecial: 'K',
        ltSpecial: 'K',
      },
    },
    {
      key: 'KeyL',
      type: 'symbol',
      text: {
        en: 'l',
        enCapital: 'L',
        lt: 'l',
        ltCapital: 'L',
        enSpecial: 'L',
        ltSpecial: 'L',
      },
    },
    {
      key: 'Semicolon',
      type: 'symbol',
      text: {
        en: ';',
        enCapital: ';',
        lt: ';',
        ltCapital: ';',
        enSpecial: ':',
        ltSpecial: ':',
      },
    },
    {
      key: 'Quote',
      type: 'symbol',
      text: {
        en: "'",
        enCapital: "'",
        lt: "'",
        ltCapital: "'",
        enSpecial: '"',
        ltSpecial: '"',
      },
    },
    {
      key: 'Enter',
      type: 'function',
      text: {
        en: 'Enter',
        enCapital: 'Enter',
        lt: 'Enter',
        ltCapital: 'Enter',
        enSpecial: 'Enter',
        ltSpecial: 'Enter',
      },
      width: 'width-double',
    },
  ],
  [
    {
      key: 'ShiftLeft',
      type: 'function',
      text: {
        en: 'Shift',
        enCapital: 'Shift',
        lt: 'Shift',
        ltCapital: 'Shift',
        enSpecial: 'Shift',
        ltSpecial: 'Shift',
      },
      width: 'width-double',
    },
    {
      key: 'KeyZ',
      type: 'symbol',
      text: {
        en: 'z',
        enCapital: 'Z',
        lt: 'z',
        ltCapital: 'Z',
        enSpecial: 'Z',
        ltSpecial: 'Z',
      },
    },
    {
      key: 'KeyX',
      type: 'symbol',
      text: {
        en: 'x',
        enCapital: 'X',
        lt: 'x',
        ltCapital: 'X',
        enSpecial: 'X',
        ltSpecial: 'X',
      },
    },
    {
      key: 'KeyC',
      type: 'symbol',
      text: {
        en: 'c',
        enCapital: 'C',
        lt: 'c',
        ltCapital: 'C',
        enSpecial: 'C',
        ltSpecial: 'C',
      },
    },
    {
      key: 'KeyV',
      type: 'symbol',
      text: {
        en: 'v',
        enCapital: 'V',
        lt: 'v',
        ltCapital: 'V',
        enSpecial: 'V',
        ltSpecial: 'V',
      },
    },
    {
      key: 'KeyB',
      type: 'symbol',
      text: {
        en: 'b',
        enCapital: 'B',
        lt: 'b',
        ltCapital: 'B',
        enSpecial: 'B',
        ltSpecial: 'B',
      },
    },
    {
      key: 'KeyN',
      type: 'symbol',
      text: {
        en: 'n',
        enCapital: 'N',
        lt: 'n',
        ltCapital: 'N',
        enSpecial: 'N',
        ltSpecial: 'N',
      },
    },
    {
      key: 'KeyM',
      type: 'symbol',
      text: {
        en: 'm',
        enCapital: 'M',
        lt: 'm',
        ltCapital: 'M',
        enSpecial: 'M',
        ltSpecial: 'M',
      },
    },
    {
      key: 'Comma',
      type: 'symbol',
      text: {
        en: ',',
        enCapital: ',',
        lt: ',',
        ltCapital: ',',
        enSpecial: '<',
        ltSpecial: '<',
      },
    },
    {
      key: 'Period',
      type: 'symbol',
      text: {
        en: '.',
        enCapital: '.',
        lt: '.',
        ltCapital: '.',
        enSpecial: '>',
        ltSpecial: '>',
      },
    },
    {
      key: 'Slash',
      type: 'symbol',
      text: {
        en: '/',
        enCapital: '/',
        lt: '/',
        ltCapital: '/',
        enSpecial: '?',
        ltSpecial: '?',
      },
    },
    {
      key: 'ArrowUp',
      type: 'function',
      text: {
        en: '↑',
        enCapital: '↑',
        lt: '↑',
        ltCapital: '↑',
        enSpecial: '↑',
        ltSpecial: '↑',
      },
    },
    {
      key: 'ShiftRight',
      type: 'function',
      text: {
        en: 'Shift',
        enCapital: 'Shift',
        lt: 'Shift',
        ltCapital: 'Shift',
        enSpecial: 'Shift',
        ltSpecial: 'Shift',
      },
      width: 'width-double',
    },
  ],
  [
    {
      key: 'ControlLeft',
      type: 'function',
      text: {
        en: 'Ctrl',
        enCapital: 'Ctrl',
        lt: 'Ctrl',
        ltCapital: 'Ctrl',
        enSpecial: 'Ctrl',
        ltSpecial: 'Ctrl',
      },
      width: 'width-2',
    },
    {
      key: 'MetaLeft',
      type: 'function',
      text: {
        en: '⊞',
        enCapital: '⊞',
        lt: '⊞',
        ltCapital: '⊞',
        enSpecial: '⊞',
        ltSpecial: '⊞',
      },
    },
    {
      key: 'AltLeft',
      type: 'function',
      text: {
        en: 'Alt',
        enCapital: 'Alt',
        lt: 'Alt',
        ltCapital: 'Alt',
        enSpecial: 'Alt',
        ltSpecial: 'Alt',
      },
    },
    {
      key: 'Space',
      type: 'symbol',
      text: {
        en: ' ',
        enCapital: ' ',
        lt: ' ',
        ltCapital: ' ',
        enSpecial: ' ',
        ltSpecial: ' ',
      },
      width: 'extra-wide',
    },
    {
      key: 'AltRight',
      type: 'function',
      text: {
        en: 'Alt',
        enCapital: 'Alt',
        lt: 'Alt',
        ltCapital: 'Alt',
        enSpecial: 'Alt',
        ltSpecial: 'Alt',
      },
    },
    {
      key: 'ArrowLeft',
      type: 'function',
      text: {
        en: '←',
        enCapital: '←',
        lt: '←',
        ltCapital: '←',
        enSpecial: '←',
        ltSpecial: '←',
      },
    },
    {
      key: 'ArrowDown',
      type: 'function',
      text: {
        en: '↓',
        enCapital: '↓',
        lt: '↓',
        ltCapital: '↓',
        enSpecial: '↓',
        ltSpecial: '↓',
      },
    },
    {
      key: 'ArrowRight',
      type: 'function',
      text: {
        en: '→',
        enCapital: '→',
        lt: '→',
        ltCapital: '→',
        enSpecial: '→',
        ltSpecial: '→',
      },
    },
    {
      key: 'ControlRight',
      type: 'function',
      text: {
        en: 'Ctrl',
        enCapital: 'Ctrl',
        lt: 'Ctrl',
        ltCapital: 'Ctrl',
        enSpecial: 'Ctrl',
        ltSpecial: 'Ctrl',
      },
      width: 'width-2',
    },
  ],
];

export default layout;
