const layout = [
  [
    {
      key: 'Backquote',
      type: 'symbol',
      text: {
        en: '`',
        enCapital: '`',
        lt: '`',
        ltCapital: '`',
        special: '~',
      },
    },
    {
      key: 'Digit1',
      type: 'symbol',
      text: {
        en: '1',
        enCapital: '1',
        lt: 'ą',
        ltCapital: 'Ą',
        special: '!',
      },
    },
    {
      key: 'Digit2',
      type: 'symbol',
      text: {
        en: '2',
        enCapital: '2',
        lt: 'č',
        ltCapital: 'Č',
        special: '@',
      },
    },
    {
      key: 'Digit3',
      type: 'symbol',
      text: {
        en: '3',
        enCapital: '3',
        lt: 'ę',
        ltCapital: 'Ę',
        special: '#',
      },
    },
    {
      key: 'Digit4',
      type: 'symbol',
      text: {
        en: '4',
        enCapital: '4',
        lt: 'ė',
        ltCapital: 'Ė',
        special: '$',
      },
    },
    {
      key: 'Digit5',
      type: 'symbol',
      text: {
        en: '5',
        enCapital: '5',
        lt: 'į',
        ltCapital: 'Į',
        special: '%',
      },
    },
    {
      key: 'Digit6',
      type: 'symbol',
      text: {
        en: '6',
        enCapital: '6',
        lt: 'š',
        ltCapital: 'Š',
        special: '^',
      },
    },
    {
      key: 'Digit7',
      type: 'symbol',
      text: {
        en: '7',
        enCapital: '7',
        lt: 'ų',
        ltCapital: 'Ų',
        special: '&',
      },
    },
    {
      key: 'Digit8',
      type: 'symbol',
      text: {
        en: '8',
        enCapital: '8',
        lt: 'ū',
        ltCapital: 'Ū',
        special: '*',
      },
    },
    {
      key: 'Digit9',
      type: 'symbol',
      text: {
        en: '9',
        enCapital: '9',
        lt: '9',
        ltCapital: '9',
        special: '(',
      },
    },
    {
      key: 'Digit0',
      type: 'symbol',
      text: {
        en: '0',
        enCapital: '0',
        lt: '0',
        ltCapital: '0',
        special: ')',
      },
    },
    {
      key: 'Minus',
      type: 'symbol',
      text: {
        en: '-',
        enCapital: '-',
        lt: '-',
        ltCapital: '-',
        special: '_',
      },
    },
    {
      key: 'Equal',
      type: 'symbol',
      text: {
        en: '=',
        enCapital: '=',
        lt: 'ž',
        ltCapital: 'Ž',
        special: '+',
      },
    },
    {
      key: 'Backspace',
      type: 'function',
      text: {
        en: 'Backspace',
        enCapital: 'Backspace',
        lt: 'Backspace',
        ltCapital: 'Backspace',
        special: 'Backspace',
      },
      width: 'width-4',
    },
  ],
  [
    {
      key: 'Tab',
      type: 'function',
      text: {
        en: 'Tab',
        enCapital: 'Tab',
        lt: 'Tab',
        ltCapital: 'Tab',
        special: 'Tab',
      },
      width: 'width-2',
    },
    {
      key: 'KeyQ',
      type: 'symbol',
      text: {
        en: 'q',
        enCapital: 'Q',
        lt: 'q',
        ltCapital: 'Q',
        special: 'Q',
      },
    },
    {
      key: 'KeyW',
      type: 'symbol',
      text: {
        en: 'w',
        enCapital: 'W',
        lt: 'w',
        ltCapital: 'W',
        special: 'W',
      },
    },
    {
      key: 'KeyE',
      type: 'symbol',
      text: {
        en: 'e',
        enCapital: 'E',
        lt: 'e',
        ltCapital: 'E',
        special: 'E',
      },
    },
    {
      key: 'KeyR',
      type: 'symbol',
      text: {
        en: 'r',
        enCapital: 'R',
        lt: 'r',
        ltCapital: 'R',
        special: 'R',
      },
    },
    {
      key: 'KeyT',
      type: 'symbol',
      text: {
        en: 't',
        enCapital: 'T',
        lt: 't',
        ltCapital: 'T',
        special: 'T',
      },
    },
    {
      key: 'KeyY',
      type: 'symbol',
      text: {
        en: 'y',
        enCapital: 'Y',
        lt: 'y',
        ltCapital: 'Y',
        special: 'Y',
      },
    },
    {
      key: 'KeyU',
      type: 'symbol',
      text: {
        en: 'u',
        enCapital: 'U',
        lt: 'u',
        ltCapital: 'U',
        special: 'U',
      },
    },
    {
      key: 'KeyI',
      type: 'symbol',
      text: {
        en: 'i',
        enCapital: 'I',
        lt: 'i',
        ltCapital: 'I',
        special: 'I',
      },
    },
    {
      key: 'KeyO',
      type: 'symbol',
      text: {
        en: 'o',
        enCapital: 'O',
        lt: 'o',
        ltCapital: 'O',
        special: 'O',
      },
    },
    {
      key: 'KeyP',
      type: 'symbol',
      text: {
        en: 'p',
        enCapital: 'P',
        lt: 'p',
        ltCapital: 'P',
        special: 'P',
      },
    },
    {
      key: 'BracketLeft',
      type: 'symbol',
      text: {
        en: '[',
        enCapital: '[',
        lt: '[',
        ltCapital: '[',
        special: '{',
      },
    },
    {
      key: 'BracketRight',
      type: 'symbol',
      text: {
        en: ']',
        enCapital: ']',
        lt: ']',
        ltCapital: ']',
        special: '}',
      },
    },
    {
      key: 'Backslash',
      type: 'symbol',
      text: {
        en: '\\',
        enCapital: '\\',
        lt: '\\',
        ltCapital: '\\',
        special: '|',
      },
    },
    {
      key: 'Delete',
      type: 'function',
      text: {
        en: 'Del',
        enCapital: 'Del',
        lt: 'Del',
        ltCapital: 'Del',
        special: 'Del',
      },
      width: 'width-2',
    },
  ],
  [
    {
      key: 'CapsLock',
      type: 'function',
      text: {
        en: 'Caps',
        enCapital: 'Caps',
        lt: 'Caps',
        ltCapital: 'Caps',
        special: 'Caps',
      },
      width: 'width-4',
    },
    {
      key: 'KeyA',
      type: 'symbol',
      text: {
        en: 'a',
        enCapital: 'A',
        lt: 'a',
        ltCapital: 'A',
        special: 'A',
      },
    },
    {
      key: 'KeyS',
      type: 'symbol',
      text: {
        en: 's',
        enCapital: 'S',
        lt: 's',
        ltCapital: 'S',
        special: 'S',
      },
    },
    {
      key: 'KeyD',
      type: 'symbol',
      text: {
        en: 'd',
        enCapital: 'D',
        lt: 'd',
        ltCapital: 'D',
        special: 'D',
      },
    },
    {
      key: 'KeyF',
      type: 'symbol',
      text: {
        en: 'f',
        enCapital: 'F',
        lt: 'f',
        ltCapital: 'F',
        special: 'F',
      },
    },
    {
      key: 'KeyG',
      type: 'symbol',
      text: {
        en: 'g',
        enCapital: 'G',
        lt: 'g',
        ltCapital: 'G',
        special: 'G',
      },
    },
    {
      key: 'KeyH',
      type: 'symbol',
      text: {
        en: 'h',
        enCapital: 'H',
        lt: 'h',
        ltCapital: 'H',
        special: 'H',
      },
    },
    {
      key: 'KeyJ',
      type: 'symbol',
      text: {
        en: 'j',
        enCapital: 'J',
        lt: 'j',
        ltCapital: 'J',
        special: 'J',
      },
    },
    {
      key: 'KeyK',
      type: 'symbol',
      text: {
        en: 'k',
        enCapital: 'K',
        lt: 'k',
        ltCapital: 'K',
        special: 'K',
      },
    },
    {
      key: 'KeyL',
      type: 'symbol',
      text: {
        en: 'l',
        enCapital: 'L',
        lt: 'l',
        ltCapital: 'L',
        special: 'L',
      },
    },
    {
      key: 'Semicolon',
      type: 'symbol',
      text: {
        en: ';',
        enCapital: ';',
        lt: ';',
        ltCapital: ';',
        special: ':',
      },
    },
    {
      key: 'Quote',
      type: 'symbol',
      text: {
        en: "'",
        enCapital: "'",
        lt: "'",
        ltCapital: "'",
        special: '"',
      },
    },
    {
      key: 'Enter',
      type: 'function',
      text: {
        en: 'Enter',
        enCapital: 'Enter',
        lt: 'Enter',
        ltCapital: 'Enter',
        special: 'Enter',
      },
      width: 'width-3',
    },
  ],
  [
    {
      key: 'ShiftLeft',
      type: 'function',
      text: {
        en: 'Shift',
        enCapital: 'Shift',
        lt: 'Shift',
        ltCapital: 'Shift',
        special: 'Shift',
      },
      width: 'width-4',
    },
    {
      key: 'KeyZ',
      type: 'symbol',
      text: {
        en: 'z',
        enCapital: 'Z',
        lt: 'z',
        ltCapital: 'Z',
        special: 'Z',
      },
    },
    {
      key: 'KeyX',
      type: 'symbol',
      text: {
        en: 'x',
        enCapital: 'X',
        lt: 'x',
        ltCapital: 'X',
        special: 'X',
      },
    },
    {
      key: 'KeyC',
      type: 'symbol',
      text: {
        en: 'c',
        enCapital: 'C',
        lt: 'c',
        ltCapital: 'C',
        special: 'C',
      },
    },
    {
      key: 'KeyV',
      type: 'symbol',
      text: {
        en: 'v',
        enCapital: 'V',
        lt: 'v',
        ltCapital: 'V',
        special: 'V',
      },
    },
    {
      key: 'KeyB',
      type: 'symbol',
      text: {
        en: 'b',
        enCapital: 'B',
        lt: 'b',
        ltCapital: 'B',
        special: 'B',
      },
    },
    {
      key: 'KeyN',
      type: 'symbol',
      text: {
        en: 'n',
        enCapital: 'N',
        lt: 'n',
        ltCapital: 'N',
        special: 'N',
      },
    },
    {
      key: 'KeyM',
      type: 'symbol',
      text: {
        en: 'm',
        enCapital: 'M',
        lt: 'm',
        ltCapital: 'M',
        special: 'M',
      },
    },
    {
      key: 'Comma',
      type: 'symbol',
      text: {
        en: ',',
        enCapital: ',',
        lt: ',',
        ltCapital: ',',
        special: '<',
      },
    },
    {
      key: 'Period',
      type: 'symbol',
      text: {
        en: '.',
        enCapital: '.',
        lt: '.',
        ltCapital: '.',
        special: '>',
      },
    },
    {
      key: 'Slash',
      type: 'symbol',
      text: {
        en: '/',
        enCapital: '/',
        lt: '/',
        ltCapital: '/',
        special: '?',
      },
    },
    {
      key: 'ArrowUp',
      type: 'function',
      text: {
        en: '↑',
        enCapital: '↑',
        lt: '↑',
        ltCapital: '↑',
        special: '↑',
      },
    },
    {
      key: 'ShiftRight',
      type: 'function',
      text: {
        en: 'Shift',
        enCapital: 'Shift',
        lt: 'Shift',
        ltCapital: 'Shift',
        special: 'Shift',
      },
      width: 'width-4',
    },
  ],
  [
    {
      key: 'ControlLeft',
      type: 'function',
      text: {
        en: 'Ctrl',
        enCapital: 'Ctrl',
        lt: 'Ctrl',
        ltCapital: 'Ctrl',
        special: 'Ctrl',
      },
      width: 'width-2',
    },
    {
      key: 'MetaLeft',
      type: 'function',
      text: {
        en: '⊞',
        enCapital: '⊞',
        lt: '⊞',
        ltCapital: '⊞',
        special: '⊞',
      },
    },
    {
      key: 'AltLeft',
      type: 'function',
      text: {
        en: 'Alt',
        enCapital: 'Alt',
        lt: 'Alt',
        ltCapital: 'Alt',
        special: 'Alt',
      },
    },
    {
      key: 'Space',
      type: 'symbol',
      text: {
        en: '',
        enCapital: '',
        lt: '',
        ltCapital: '',
        special: '',
      },
      width: 'extra-wide',
    },
    {
      key: 'AltRight',
      type: 'function',
      text: {
        en: 'Alt',
        enCapital: 'Alt',
        lt: 'Alt',
        ltCapital: 'Alt',
        special: 'Alt',
      },
    },
    {
      key: 'ArrowLeft',
      type: 'function',
      text: {
        en: '←',
        enCapital: '←',
        lt: '←',
        ltCapital: '←',
        special: '←',
      },
    },
    {
      key: 'ArrowDown',
      type: 'function',
      text: {
        en: '↓',
        enCapital: '↓',
        lt: '↓',
        ltCapital: '↓',
        special: '↓',
      },
    },
    {
      key: 'ArrowRight',
      type: 'function',
      text: {
        en: '→',
        enCapital: '→',
        lt: '→',
        ltCapital: '→',
        special: '→',
      },
    },
    {
      key: 'ControlRight',
      type: 'function',
      text: {
        en: 'Ctrl',
        enCapital: 'Ctrl',
        lt: 'Ctrl',
        ltCapital: 'Ctrl',
        special: 'Ctrl',
      },
      width: 'width-2',
    },
  ],
];

export default layout;
